website/classify/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^file/$', 'classify.views.classify_file', name='file'),
    url(r'^sentence/$', 'classify.views.classify_sentence', name='sentence'),
    url(r'^post/$', 'classify.views.classify_post', name='post'),

]

website/frontend/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'frontend.views.home', name='home'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^classify/', include('classify.urls', namespace='classify')),
    url(r'^', include('frontend.urls', namespace='frontend')),
]

website/classify/models.py
from django.db import models

# Create your models here.

website/frontend/models.py
from django.db import models

# Create your models here.

website/classify/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

website/classify/views.py
from django.shortcuts import render
from .forms import UploadFileForm
from .libs.get_data_by_url import get_post_info


def classify_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file_content = form.files['file'].read()
    else:
        file_content = ''
    return render(request, 'classify/chart.html', {'data': {'positive': 10, 'negative': 20, 'text': file_content}})


def classify_sentence(request):
    if request.method == 'POST':
        sentence = request.POST['sentence']

    return render(request, 'classify/chart.html', {'data': {'positive': 10, 'negative': 20, 'text': sentence}})


def classify_post(request):
    if request.method == 'POST':
        post_url = request.POST['post_url']
        data = {}

        with get_post_info() as x:
            data = x.get_post_data_from_url(post_url)

    return render(request, 'classify/chart.html', {'data': {'positive': 10, 'negative': 20, 'text':data}})

website/frontend/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'frontend/index.html', {})

website/classify/templates/classify/chart.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
data: {{ data }}

</body>
</html>

website/frontend/templates/_layout/footer.html
<footer>
    <div class="container">
        <div class="row">
            <p>Copyright © 2015 Arabic Social Media Sentiment Analysis</p>
        </div>
    </div>
</footer>

website/frontend/templates/_layout/head.html
{% load static %}

<head>

    <meta charset="utf-8">
    <title>Arabic Social Media Sentiment Analysis</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- google font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,700,800' rel='stylesheet'
          type='text/css'>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
    <!-- extra css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/extra.css' %}">

</head>

website/frontend/templates/_layout/scripts.html
{% load static %}
<script src="{%  static 'js/jquery.js' %}"></script>
<script src="{%  static 'js/bootstrap.min.js' %}"></script>
<script src="{%  static 'js/wow.min.js' %}"></script>
<script src="{%  static 'js/jquery.singlePageNav.min.js' %}"></script>
<script src="{%  static 'js/extrajs.js' %}"></script>
<script src="{%  static 'js/custom.js' %}"></script>

website/frontend/templates/_layout/sections/about.html
{% load static %}
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-12 wow bounceIn">
                <h2 class="text-uppercase"> About Us</h2>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Mahmoud Elgayyar</h3>
                <h5> Professor at Faculty of computer and infromatics Seuz Canal University</h5>
                <h5>Position: Manager</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Sara El Sayed</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Ahmed Magdy</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Amany Samy</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Mohamed Taha</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Eman Kamal</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Mahmoud Ahmed</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Maha El-rayss</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Ahmed Shalash</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Eman Mostafa</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>

            <div class="col-md-3 wow fadeInUp templatemo-box" data-wow-delay="0.3s">
                <img src="{% static 'images/member-img.jpg' %}" class="img-responsive" alt="member img">

                <h3 class="text-uppercase">Mohamed Sabri</h3>
                <h5>Faculty: Seuz Canal University </h5>
                <h5>Position: Software Developer</h5>
                <h5>contact: <a href="#" onclick="return false;">here</a></h5>
            </div>
        </div>
    </div>
    </div>
</section>

website/frontend/templates/_layout/sections/contact.html
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                <h2 class="text-uppercase">Contact Us</h2>

                <p>please complete the form for sponsorships or other requests.</p>
                <address>
                    <p><i class="fa fa-map-marker"></i>1234 Street Name, City Name, United States</p>

                    <p><i class="fa fa-phone"></i> 0992 234234 / 0234 234234</p>

                    <p><i class="fa fa-envelope-o"></i>SentimentArabicSocial@gmail.com</p>
                </address>
            </div>
            <div class="col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                <div class="contact-form">
                    <form action="#" method="post">
                        <div class="col-md-6">
                            <input type="text" class="form-control" placeholder="Name">
                        </div>
                        <div class="col-md-6">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <div class="col-md-12">
                            <input type="text" class="form-control" placeholder="Subject">
                        </div>
                        <div class="col-md-12">
                            <textarea class="form-control" placeholder="Message" rows="4"></textarea>
                        </div>
                        <div class="col-md-8">
                            <input type="submit" class="form-control text-uppercase" value="Send">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

website/frontend/templates/_layout/sections/feature.html
{% load static %}
<section id="feature">
    <div class="container">
        <div class="row">
            <div class="col-md-6 wow fadeInLeft" data-wow-delay="0.6s">
                <h2 class="text-uppercase">Our Software Features</h2>

                <p>Our software has many features which help you understand your data fast and simply.</p>

                <p><span><i class="fa fa-quote-left"></i></span> Using more than one classifier gives you good accuracy
                    and low error rate for you output.</p>

                <p><span><i class="fa fa-quote-left"></i></span> Visulaized Results give you good , fast and easy
                    understand for your output.</p>
            </div>
            <div class="col-md-6 wow fadeInRight" data-wow-delay="0.6s">
                <img src="{% static 'images/feature-img.png' %}" class="img-responsive" alt="feature img">
            </div>
        </div>
    </div>
</section>

website/frontend/templates/_layout/sections/feature_1.html
{% load static %}
<section id="feature1">
    <div class="container">
        <div class="row">
            <div class="col-md-6 wow fadeInLeft" data-wow-delay="0.6s">
                <img src="{% static 'images/feature2-img.jpg' %}" class="img-responsive" alt="feature img">
            </div>
            <div class="col-md-6 wow fadeInRight" data-wow-delay="0.6s">
                <h2 class="text-uppercase">More of Features</h2>

                <p>There are more of features for our software which related with the type and form of the input
                    data.</p>

                <p><span><i class="fa fa-quote-left"></i></span>Our Software can deal with all forms of Arabic Writing
                    like Modern Standard Arabic(MSA),Dialectal Arabic(DA) and Franco-Arabic.

                <p><span><i class="fa fa-quote-left"></i></span>You can enter your inpute by many ways: </p>

                <div>
                    <span><li class="fa fa-spinner"></li></span>insert sentence manually and classify it.
                </div>
                <div>
                    <span><li class="fa fa-spinner"></li></span> upload data as txt file.
                </div>
                <div>
                    <span><li class="fa fa-spinner"></li></span> collect data from facebook page OR specify post Link.
                </div>

            </div>
        </div>
    </div>
</section>

website/frontend/templates/_layout/sections/home.html
{% load static %}
<section id="home">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10 wow fadeIn" data-wow-delay="0.3s">
                    <h1 class="text-upper">What's Arabic Social Media Sentiment Analysis</h1>

                    <p class="tm-white">we now have a huge volume of opinionated arabic data in the social media on the
                        Web. Arabic Social Media Sentiment Analysis is focuses on opinions which express positive or
                        negative sentiments. Helping you with simple and awesome visualization for data analysis.
                        <img src="{% static 'images/dataChart-img.png' %}" class="img-responsive" alt="home img">
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
</section>

website/frontend/templates/_layout/sections/pricing.html
<section id="pricing">
    <div class="container">
        <div class="row">
            <div class="col-md-12 wow bounceIn">
                <h2 class="text-uppercase">Try it</h2>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing text-uppercase">
                    <div class="pricing-title">
                        <h4>insert sentence manually</h4>
                    </div>
                    <form id="sentence-form" action="{% url 'classify:sentence' %}" method="post">

                        <ul>
                            <li>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        {% csrf_token %}
                                        <input type="text" name="sentence" class="form-control"
                                               placeholder="insert sentence..."
                                               id="sentenc-input">
                                    </div>
                                </div>

                            </li>
                        </ul>
							 <span class="input-group-btn">
						        <button class="btn btn-default" type="submit" id="sentence-button">Classify</button>
						     </span>
                    </form>

                </div>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing active text-uppercase">
                    <div class="pricing-title">
                        <h4>upload data as txt file</h4>
                    </div>
                    <form id="file-form" action="{% url 'classify:file' %}"
                          method="post" enctype="multipart/form-data">
                        <ul>
                            <li>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        {#                                    <input type="text" class="form-control col-md-8" readonly>#}

							                <span class="input-group-btn col-md-4">
							                    <span class="btn btn-primary btn-file">
							                        Add File &hellip;

                                                    {% csrf_token %}
                                                        <input
                                                                name="file"
                                                                type="file"
                                                                id="file-input">
							                    </span>
							                </span>

                                    </div>
                                </div>
                            </li>
                            <li>
									<span class="input-group-btn">
						        <button class="btn btn-default" type="submit">Classify</button>
						     </span>
                            </li>
                        </ul>
                    </form>


                </div>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-delay="0.6s">
                <div class="pricing text-uppercase">
                    <div class="pricing-title">
                        <h4>Collect data from facebook</h4>
                    </div>
                    <form id="post-form" action="{% url 'classify:post' %}" method="post">

                        <ul>
                            <li>
                                <div class="col-md-12">
                                    <div class="input-group">
                                        {% csrf_token %}
                                        <input type="text" class="form-control" placeholder="insert post link ..."
                                               id="post-url-input" name="post_url">
                                    </div>
                                </div>

                            </li>
                        </ul>
							 <span class="input-group-btn">
						        <button class="btn btn-default" type="submit" id="post-url-button">Classify</button>
						     </span>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

website/frontend/templates/frontend/base.html
{% load static %}
{% load frontend_layout %}
<!DOCTYPE html>
<html lang="en">
{% layout_head %}

<body>
<!-- start preloader -->
<div class="preloader">
    <div class="sk-spinner sk-spinner-rotating-plane"></div>
</div>
<!-- end preloader -->
<!-- start navigation -->
<nav class="navbar navbar-default navbar-fixed-top templatemo-nav" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
            </button>
            <img src="{% static 'images/LOGO.jpg' %}" class="img-responsive" alt="member img">
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right text-uppercase">
                {% block navitems %}
                    <li><a href="#home">Home</a></li>
                    <li><a href="#feature">Features</a></li>
                    <li><a href="#pricing">Demo</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                {% endblock %}

            </ul>
        </div>
    </div>
</nav>
<!-- end navigation -->
{% block sections %}
    <!-- start home -->
    {% section_home %}
    <!-- end home -->
    {% section_feature %}
    <!-- start feature -->

    <!-- end feature -->

    <!-- start feature1 -->
    {% section_feature_1 %}
    <!-- end feature1 -->

    <!-- start Try it -->
    {% section_pricing %}
    <!-- end try it -->

    <!-- start about -->
    {% section_about %}
    <!-- end about -->

    <!-- start contact -->
    {% section_contact %}
    <!-- end contact -->

    <!-- start footer -->
    {% layout_footer %}
    <!-- end footer -->
    {% load_scripts %}
{% endblock %}
</body>

</html>

website/frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}